import { Player } from '@/types'

export const initialPlayers: Player[] = [
  { id: 1, name: 'D4rzk', defaultLine: 11 },
  { id: 2, name: 'Kangaroo66', defaultLine: 11 },
  { id: 3, name: 'krasi1975', defaultLine: 10 },
  { id: 4, name: 'Mino', defaultLine: 10 },
  // { id: 5, name: 'Pejda', defaultLine: 9 },
  // { id: 6, name: 'iVáclav', defaultLine: 9 },
  // { id: 7, name: 'cabrisk77', defaultLine: 8 },
  // { id: 8, name: 'Leoš', defaultLine: 8 },
  // { id: 9, name: 'Jiří', defaultLine: 7 },
  // { id: 10, name: 'Stony', defaultLine: 7 },
  // { id: 11, name: 'Rezzi', defaultLine: 6 },
  // { id: 12, name: 'Makovecz', defaultLine: 6 },
  // { id: 13, name: 'Mahtiel', defaultLine: 5 },
  // { id: 14, name: 'michal', defaultLine: 5 },
  // { id: 15, name: 'Milan123', defaultLine: 4 },
  // { id: 16, name: 'Alikovna', defaultLine: 4 },
  // { id: 17, name: 'Nedvěd', defaultLine: 3 },
  // { id: 18, name: 'nero82', defaultLine: 3 },
  // { id: 19, name: 'basters007', defaultLine: 2 },
  // { id: 20, name: 'Lukas227', defaultLine: 2 },
  // { id: 21, name: 'Jarin17', defaultLine: 1 },
  // { id: 22, name: 'Dandus', defaultLine: 1 },
]
